spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: password
  sql:
    init:
      platform: mysql
      schema-locations: classpath:db/mysql/db-schema.sql
      data-locations: classpath:db/initial-data.sql
      mode: always
