spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgresql
      schema-locations: classpath:db/postgres/db-schema.sql
      data-locations: classpath:db/initial-data.sql
      mode: always
